<img src="assets/images/photo.png"><strong>Barykin Viktor Nikola&iuml;evitch</strong> est n&eacute; en 1947 en Bi&eacute;lorussie, dans le village de Govezna, region de Stolbtsy. Il a pass&eacute; la majeure partie de sa jeunesse avec ses parents, son fr&egrave;re et ses trois s&oelig;urs dans le village de Berezha, region de Dzerjinsk.
Il a termin&eacute; ses &eacute;tudes secondaires avec mention excellent dans la ville de Fanipol, region de Dzerjinsk. Il a ensuite poursuivi ses &eacute;tudes &agrave; l&rsquo;Universit&eacute; d&rsquo;&Eacute;tat de Bi&eacute;lorussie &agrave; Minsk, o&ugrave; le concours d&rsquo;entr&eacute;e comptait 13 candidats par place.</p>
<p>En 1969, il a obtenu un dipl&ocirc;me de sp&eacute;cialiste en physique nucl&eacute;aire th&eacute;orique, avec le droit d&rsquo;enseigner la physique dans les &eacute;coles secondaires.</p>
<p>Apr&egrave;s l&rsquo;universit&eacute;, il a consacr&eacute; quatre ans &agrave; des activit&eacute;s publiques. Il a d&rsquo;abord travaill&eacute; comme chef du d&eacute;partement d&rsquo;organisation, puis comme deuxi&egrave;me secr&eacute;taire du comit&eacute; de Komsomol &agrave; Dzerjinsk. Pendant un an, il a &eacute;galement enseign&eacute; la physique dans une &eacute;cole secondaire &agrave; Fanipol. Tout au long de cette p&eacute;riode, il s&rsquo;est consacr&eacute; &agrave; sa famille, en portant une attention particuli&egrave;re &agrave; sa fille Olga et &agrave; son fils Oleg. Son &eacute;pouse, Tamara, enseignait l&rsquo;anglais et le fran&ccedil;ais. Cette harmonie familiale lui a permis, durant ses recherches scientifiques personnelles, d&rsquo;aborder d&rsquo;une mani&egrave;re nouvelle la th&eacute;orie de la relativit&eacute; et de g&eacute;n&eacute;raliser partiellement l&rsquo;&eacute;lectrodynamique de Maxwell.</p>
<p>Ses camarades d&rsquo;universit&eacute; travaillaient tous &agrave; l&rsquo;Acad&eacute;mie des sciences de la R&eacute;publique de Bi&eacute;lorussie, et l&rsquo;ont progressivement entra&icirc;n&eacute; dans la vie scientifique. Il a commenc&eacute; avec des fonctions scientifiques de base &agrave; l&rsquo;Institut de transfert de chaleur et de masse. Cette activit&eacute; &eacute;tait &agrave; la fois diversifi&eacute;e et tr&egrave;s intense.</p>
<p>Il a eu la chance de travailler dans des conditions particuli&egrave;rement favorables au sein du laboratoire de transfert d&rsquo;&eacute;nergie, dirig&eacute; par son mentor, l&rsquo;acad&eacute;micien O.G. Martynenko. Celui-ci l&rsquo;encourageait non seulement &agrave; ex&eacute;cuter des contrats de recherche, mais aussi &agrave; s&rsquo;impliquer activement dans des travaux fondamentaux par le biais de discussions et de participations &agrave; des conf&eacute;rences et des &eacute;coles scientifiques. C&rsquo;est lui qui lui a dit un jour : &laquo; Tu souhaites cr&eacute;er une th&eacute;orie des atomes de lumi&egrave;re et de gravitation ? Vas-y ! &raquo;</p>
<p>Pour y parvenir, il &eacute;tait n&eacute;cessaire de g&eacute;n&eacute;raliser la th&eacute;orie de l&rsquo;espace-temps et de comprendre la place des objets structuraux dans les mod&egrave;les de calcul des sciences naturelles. Il a pu r&eacute;aliser quelques avanc&eacute;es en la mati&egrave;re, publi&eacute;es dans les travaux de l&rsquo;Institut sous forme de pr&eacute;publications, d&rsquo;articles et de livres. Les r&eacute;sultats de ses recherches ont &eacute;t&eacute; pr&eacute;sent&eacute;s lors de deux conf&eacute;rences internationales sur la th&eacute;orie du temps et de l&rsquo;espace &agrave; Leningrad.</p>
<p>Il a &eacute;galement effectu&eacute; un stage &agrave; l&rsquo;Institut de physique Lebedev de l&rsquo;Acad&eacute;mie des sciences de Russie (FIAN). Ses &eacute;changes avec le futur laur&eacute;at du prix Nobel V.L. Ginzburg et ses &eacute;l&egrave;ves, les docteurs A.N. Stolyarov et B.M. Bolotovski, ont enrichi et corrig&eacute; son travail scientifique. D&rsquo;autres discussions personnelles avec le g&eacute;nial D.D. Ivanenko, l&rsquo;un des premiers &agrave; avoir pr&eacute;dit l&rsquo;existence du neutron, ainsi qu&rsquo;avec N.Kh. Ibraimov, sp&eacute;cialiste des &eacute;quations diff&eacute;rentielles, ont &eacute;galement stimul&eacute; sa r&eacute;flexion.</p>
<p>En 2001, il a publi&eacute; un manuel p&eacute;dagogique pour les &eacute;tudiants des &eacute;tablissements d&rsquo;enseignement sup&eacute;rieur intitul&eacute; &laquo; L&rsquo;atome de lumi&egrave;re &raquo;, imprim&eacute; par la maison d&rsquo;&eacute;dition Belpoligraf de l&rsquo;administration pr&eacute;sidentielle de la R&eacute;publique de Bi&eacute;lorussie.</p>
<p>En 2005, il a publi&eacute; son livre &laquo; L&rsquo;&eacute;lectrodynamique de Maxwell sans la relativit&eacute; d&rsquo;Einstein &raquo; &agrave; Moscou (&Eacute;ditions Editorial URSS).</p>
<p>La m&ecirc;me ann&eacute;e, il a &eacute;t&eacute; invit&eacute; par la Soci&eacute;t&eacute; de physique d&rsquo;Allemagne &agrave; participer aux c&eacute;l&eacute;brations du 100e anniversaire des travaux d&rsquo;Einstein sur la th&eacute;orie de la relativit&eacute; et l&rsquo;effet photo&eacute;lectrique, et a pris part aux discussions &agrave; Berlin.</p>
<p>De 2005 &agrave; 2020, il a poursuivi ses travaux pour &eacute;laborer des mod&egrave;les de math&eacute;matiques non-associatives. Bien qu&rsquo;il ait publi&eacute; plusieurs essais sur le sujet, il n&rsquo;a pas obtenu de r&eacute;sultats approfondis et d&eacute;finitifs &agrave; cette &eacute;poque.</p>
<p>Entre 2020 et 2025, il a publi&eacute; 13 monographies consacr&eacute;es aux ensembles d&rsquo;objets. Dans ces travaux, des matrices de diff&eacute;rentes dimensions et &agrave; structure complexe forment des ensembles finis ferm&eacute;s selon un spectre d&rsquo;op&eacute;rations associatives et partiellement associatives. Leurs propri&eacute;t&eacute;s fonctionnelles sont non seulement uniques, mais inaccessibles aux mod&egrave;les classiques ou hypercomplexes. Ces mod&egrave;les peuvent &ecirc;tre appliqu&eacute;s &agrave; la mod&eacute;lisation du vivant, en associant les interactions physiologiques et informationnelles. Ces nouveaux ensembles ont &eacute;t&eacute; nomm&eacute;s &laquo; jardins &raquo; et prolongent les m&eacute;thodes des champs.</p>
<p>Il a &eacute;galement d&eacute;fini leur place dans les mod&egrave;les de calcul des sciences naturelles.</p>
