<img src="assets/images/photo.png"><strong>Viktor Nikolaevich Barykin</strong> was born in 1947 in Belarus, in the village of Govezna, Stolbtsy district. He spent most of his youth with his parents, brother, and three sisters in the village of Berezha, Dzerzhinsk district.
He graduated with honors from high school in the town of Fanipol, Dzerzhinsk district. He then continued his studies at the Belarusian State University in Minsk, where the competition for admission was 13 applicants per place.</p>
<p>In 1969, he received a specialist diploma in theoretical nuclear physics, with the right to teach physics at the secondary school level.</p>
<p>After graduating, he devoted four years to public service. He initially worked as head of the organizational department and later as second secretary of the district committee of the Komsomol in Dzerzhinsk. For one year, he also taught physics at a secondary school in Fanipol. During this time, he focused on family life, giving special attention to his daughter Olga and his son Oleg. His wife, Tamara, worked as a teacher of English and French. This family harmony allowed him, during his independent scientific work, to approach the theory of relativity from a new perspective and partially generalize Maxwell&rsquo;s electrodynamics.</p>
<p>All his university friends worked at the Academy of Sciences of the Republic of Belarus, gradually drawing him into scientific life. He started at junior scientific levels at the Institute of Heat and Mass Transfer. This activity was both diverse and very dynamic.</p>
<p>He was especially fortunate with the conditions and subject matter of his research at the Energy Transfer Laboratory, led by his mentor, Academician O.G. Martynenko. He not only permitted work on scientific contracts but also encouraged participation in solving fundamental problems through discussions and conference trips. He was the first to say: &ldquo;Do you want to create a theory of light atoms and gravitation? Go ahead.&rdquo;</p>
<p>To achieve this, it was necessary to generalize the theory of space and time and to understand the place of structural objects in computational models of natural sciences. He managed to make some progress in this field, which was published in the Institute&rsquo;s proceedings, preprints, articles, and books. The results were presented at two international conferences on the theory of time and space in Leningrad.</p>
<p>A research internship at the Lebedev Physical Institute (FIAN) of the Russian Academy of Sciences was also valuable. His direct contacts with the future Nobel laureate V.L. Ginzburg and his students, Doctors A.N. Stolyarov and B.M. Bolotovsky, helped refine his work. Discussions with the brilliant D.D. Ivanenko, one of the first to predict the neutron, as well as with N.Kh. Ibraimov, who provided insights into the mathematics of differential equations, further stimulated his research.</p>
<p>In 2001, he published a textbook for university students entitled <em>The Atom of Light</em>, printed by the Belpoligraf publishing house of the Presidential Administration of the Republic of Belarus.</p>
<p>In 2005, he published his book <em>Maxwell&rsquo;s Electrodynamics without Einstein&rsquo;s Relativity</em> in Moscow (Editorial URSS).</p>
<p>That same year, he was invited by the German Physical Society to the centennial celebration of Einstein's works on relativity and the photoelectric effect, and he took part in discussions held in Berlin.</p>
<p>From 2005 to 2020, he worked on developing models of non-associative mathematics. Although he published several attempts, no deep or definitive results were achieved during that period.</p>
<p>Between 2020 and 2025, he published 13 monographs on object set theory. In these works, matrices of various dimensions and complex structures form finite sets closed under a spectrum of associative and partially associative operations. Their functional properties are not only unique but also unattainable within classical or hypercomplex models. These models can be applied to the simulation of living organisms, combining physiological and informational interactions. These new sets were named "gardens," extending the methods and approaches of field theory.</p>
<p>He also identified their role within computational models of natural sciences.</p>